title: "Dr. Patrick Stöckle"
description: "The CV of Patrick Stöckle."

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "true"
resume_name:                    "Dr. Patrick Stöckle"
resume_title:                   "Security Researcher – Software Engineer"
resume_contact_email:           "patrick.stoeckle@posteo.de"

resume_header_intro: >-
  <p>
  I'm a research scientist at <a href="https://www.siemens.com/global/en/company/innovation/siemens-core-technologies/cybersecurity-trust.html">Siemens Technology - Cybersecurity & Trust</a>
  and working there as an expert for cloud and container security.
  As a researcher in IT security and software engineering, I have published several articles as a first author, notably two A* papers.
  I received my PhD in Informatics from the <a href="https://www.tum.de/en/">Technical University of Munich (TUM)</a> in 2024.
  During my PhD, I worked 4 years on an
  <a href="https://www.cs.cit.tum.de/sse/forschung/hardening-security-configuration/">
  industry-funded project about security configuration</a>, and was for 4 years (2019 – 2022)
  the leading teaching assistant for the course
  <a href="https://campus.tum.de/tumonline/WBMODHB.wbShowMHBReadOnly?pKnotenNr=460596">Security Engineering</a>.
  Thus, I have profound knowledge of IT security from an industrial and academic perspective.
  Before that I did my bachelor' and master's degree at the <a href="https://www.kit.edu/english/index.php">Karlsruhe Institute of Technology (KIT)</a>
  with a strong focus on IT Security, Software Engineering, and Mathematics.
  As a programmer, I have more than 10 years of programming experience in different languages.
  Furthermore, I can offer excellent software engineering and team collaboration skills.
  </p>
resume_looking_for_work:        "yes"

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true
resume_section_publications:    true
resume_section_talks:           true
resume_section_teaching:        true
resume_section_certification:   true

resume_social_links:
  resume_github_url:            "https://github.com/pstoeckle"
  resume_linkedin_url:          "https://www.linkedin.com/in/patrick-stoeckle/"
  resume_website_url:           "https://pstoeckle.github.io/"
  resume_researchgate_url:      "https://www.researchgate.net/profile/Patrick-Stoeckle-2"
  resume_google_scholar_url:    "https://scholar.google.com/citations?user=rq9oDIoAAAAJ"
  resume_google_orcid_url:      "https://orcid.org/0000-0003-0193-5871"
resume_print_social_links:      true

resume_theme:                   default

resume_keys_openpgp_org_link: https://keys.openpgp.org/vks/v1/by-fingerprint/CBB37DF57324F4F1C2412A08B0A74B64D56B96E7
