title: "Patrick Stöckle"
description: "The CV of Patrick Stöckle."

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "true"
resume_name:                    "Patrick Stöckle"
resume_name_title:              "M.Sc."
resume_title:                   "Security Researcher – Software Engineer"
resume_contact_email:           "patrick.stoeckle@posteo.de"


display_header_contact_info:    "false"

resume_header_intro: >
  <p>I am almost finished with my Ph.D. in Informatics and currently looking for a job.
  As a researcher, I have published several articles during my Ph.D., notably two A* 
  papers as a first author. As a programmer, I have more than 10 years of programming
  experience in different languages. Furthermore, I can offer excellent software
  engineering and team collaboration skills.
  </p>
resume_looking_for_work:        "yes"

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true
resume_section_publications:    true
resume_section_talks:           true

resume_social_links:
  resume_github_url:            "https://github.com/pstoeckle"
  resume_twitter_url:           "https://twitter.com/p_stoeckle"
  resume_linkedin_url:          "https://www.linkedin.com/in/patrick-stoeckle/"
  resume_website_url:           "https://pstoeckle.github.io/"
  resume_researchgate_url:      "https://www.researchgate.net/profile/Patrick-Stoeckle-2"
  resume_google_scholar_url:    "https://scholar.google.com/citations?user=rq9oDIoAAAAJ"
resume_print_social_links:      true

resume_theme:                   default
