title: "Patrick Stöckle"
description: "The CV of Patrick Stöckle."

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "true"
resume_name:                    "Patrick Stöckle"
resume_title:                   "Security Researcher – Software Engineer"
resume_contact_email:           "patrick.stoeckle@posteo.de"

resume_header_intro: >
  <p>
  As a researcher in IT security and software engineering, I have published several articles as a first author, notably two A* papers.
  During my time at the Technical University of Munich (TUM), I worked 4 years on an industry-funded project about security configuration.
  Furthermore, I was for 4 years (2019 – 2022) the leading teaching assistant for the course Security Engineering.
  Thus, I have profound knowledge of IT security from an industrial and academic perspective.
  As a programmer, I have more than 10 years of programming experience in different languages.
  Furthermore, I can offer excellent software engineering and team collaboration skills.
  </p>
resume_looking_for_work:        "yes"

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true
resume_section_publications:    true
resume_section_talks:           true
resume_section_teaching:        true

resume_social_links:
  resume_github_url:            "https://github.com/pstoeckle"
  resume_twitter_url:           "https://twitter.com/p_stoeckle"
  resume_linkedin_url:          "https://www.linkedin.com/in/patrick-stoeckle/"
  resume_website_url:           "https://pstoeckle.github.io/"
  resume_researchgate_url:      "https://www.researchgate.net/profile/Patrick-Stoeckle-2"
  resume_google_scholar_url:    "https://scholar.google.com/citations?user=rq9oDIoAAAAJ"
  resume_google_orcid_url:      "https://orcid.org/0000-0003-0193-5871"
resume_print_social_links:      true

resume_theme:                   default

resume_keys_openpgp_org_link: https://keys.openpgp.org/vks/v1/by-fingerprint/CBB37DF57324F4F1C2412A08B0A74B64D56B96E7
