name: "Build page with jekyll"

on: {push: {branches: [main]}}
permissions: {}
concurrency:
  group: "build-pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build site with Jekyll
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pstoeckle/pstoeckle.github.io/devcontainer:0.1.0@sha256:beadd709be934c0008b81634f3242e40196eec6248d31334dbce3cfa1c723e43
      options: --user 1001:1001
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          lfs: true
          persist-credentials: false
      - name: Build site with Jekyll
        run: |-
          set -eu

          /home/vscode/.rbenv/shims/bundle install
          /home/vscode/.rbenv/shims/bundle exec jekyll build
